apiVersion: v1
kind: Pod
metadata:
  name: pod-centos
spec: 
  containers:
  - name: cntr-centos
    image: centos
    command: 
    - /bin/bash
    - -c
    args:
    - |
      while true ; do
        date 
        sleep 5 
      done