apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  containers:
  - name: {{ .Values.container_name }}
    image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
    ports:
    - containerPort: 80