---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db-data-storage 
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce    # aka RWO
    - ReadOnlyMany     # aka ROX 
    - ReadWriteMany    # aka RWX
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs/export_rw
    server: 10.3.5.109