---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-all-by-default
  namespace: default
spec:
  podSelector: {}     # This empty map acts as a asteril-lide wildcard, apply this network policy to all pods in the given namespace
  policyTypes:
  - Ingress