---
apiVersion: v1
kind: Pod
metadata:
  name: pod-httpd
spec:
  containers:
    - name: cntr-httpd
      image: docker.io/codingbee/httpd:0.1      # here we used an image's fqdn
      imagePullPolicy: Always                       # this is to avoids using cached images
      ports:
        - containerPort: 80