apiVersion: v1
kind: Pod
metadata:
  name: pod-folder-share
spec:
  volumes: 
  - name: web-data
    emptyDir: {} 
  containers:
  - name: cntr-httpd
    image: httpd:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: web-data
      mountPath: /usr/local/apache2/htdocs
  - name: cntr-centos
    image: centos
    volumeMounts:
    - name: web-data
      mountPath: /mnt/webcontent
    command: ["/bin/bash", "-c"]
    args:
    - |
      while true ; do
        echo "$(date) - New content added" >> /mnt/webcontent/index.html
        sleep 5 
      done