---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-countdown
spec:
  completions: 4  # This means run the job 4 times as part of a run. The default is 1.
  parallelism: 2  # specifies how many pods can run simultaneously in parrallel. The default is 1.
  template:
    spec:
      containers:
        - name: cntr-countdown
          image: centos:latest
          command:
            - "bin/bash"
            - "-c"
            - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; sleep 10 ; done"
      restartPolicy: Never
    
      

