---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-read  
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io     # this is a fixed string
  kind: Role
  name: role-read
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io    # this is a fixed string
    name: employee