---
apiVersion: v1
kind: Pod
metadata:
  name: pod-alpine-default
spec:
  containers:
    - name: cntr-alpine
      image: alpine
      command: ["sh", "-c"]
      args:
        - |
          while true ; do
            date 
            sleep 10 
          done