---
apiVersion: v1
kind: Pod
metadata:
  name: pod-privileged
spec:
  containers:
    - name: cntr-alpine
      image: alpine
      securityContext:
        privileged: true                  # Add this line
      command: ["sh", "-c"]
      args:
        - |
          while true ; do
            date
            sleep 10 
          done