---
apiVersion: v1
kind: Pod
metadata:
  name: pod-readonlyrootfs
spec:
  containers:
    - name: cntr-alpine
      image: alpine
      securityContext:
        readOnlyRootFilesystem: true                 # We add this line
      command: ["sh", "-c"]
      args:
        - |
          while true ; do
            date
            sleep 10 
          done