---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-httpd
  labels:
    app: httpd_webserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd_webserver
  template:
    metadata:
      labels:
        app: httpd_webserver
    spec:
      nodeName: kube-worker2      # Added this line
      containers:
        - name: cntr-httpd
          image: httpd:latest 
          ports:
            - containerPort: 80