---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-db-data-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard-persist     # Here we specify the storageclass to use, if no suitable preprovisioned PVs are available